Repository Decathlon/vitamin-web, pull requests merged in 2021-01, with the labels that each got.

#40 ci: init ci for PR and main build
  .github/workflows/build-main.yml
  .github/workflows/build-pr.yml
Labels: enhancement 🚀

#45 ci: deploy storybook
  .github/workflows/build-main.yml
  package.json
  packages/showcases/css/package.json
  yarn.lock
Labels: config 🛠, enhancement 🚀

#49 ci: Create sonar project properties for showcases
  .github/workflows/build-pr.yml
  packages/showcases/css/sonar-project.properties
  packages/sources/css/sonar-project.properties
  packages/sources/css/src/components/button/sonar-project.properties
  packages/sources/css/src/shared/design-tokens/sonar-project.properties
  packages/sources/css/src/shared/postcss-config/sonar-project.properties
  packages/sources/css/src/shared/tailwind-config/sonar-project.properties
  packages/sources/css/src/shared/utilities/sonar-project.properties
Labels: config 🛠

#47 fix: font-family on Typography CSS styles
  package.json
  packages/showcases/css/package.json
  packages/sources/css/package.json
  packages/sources/css/src/shared/design-tokens/package.json
  packages/sources/css/src/shared/design-tokens/src/typography.css
  packages/sources/css/src/shared/utilities/package.json
  yarn.lock
Labels: CSS 🎨, bug 🐛

#55 docs: add packages part in README
  README.md
  packages/showcases/css/README.md
  packages/sources/css/README.md
  packages/sources/css/config/postcss/README.md
  packages/sources/css/config/tailwind/README.md
  packages/sources/css/src/components/button/README.md
  packages/sources/css/src/components/button/package.json
  packages/sources/css/src/design-tokens/README.md
  packages/sources/css/src/utilities/README.md
  packages/sources/css/src/utilities/package.json
Labels: documentation 📝

#56 fix: build for Pull Requests
  .github/workflows/build-main.yml
  .github/workflows/build-pr.yml
Labels: bug 🐛, config 🛠

#57 refactor(css design tokens): typography line heights + font size from px to rem unit
  packages/showcases/css/.storybook/preview-head.html
  packages/sources/css/src/design-tokens/src/typography.css
Labels: CSS 🎨, design request 🙌, enhancement 🚀

#59 ci: versioning, git tags, changelog, releases & NPM publish packages
  .github/workflows/build-main.yml
  .github/workflows/build-pr.yml
  lerna.json
  package.json
Labels: config 🛠
